// <auto-generated />
namespace ABSOLUTE_CINEMA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RegUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202505101840490_RegUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
