// <auto-generated />
namespace ABSOLUTE_CINEMA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Movie4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movie4));
        
        string IMigrationMetadata.Id
        {
            get { return "202505102312511_Movie4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
