// <auto-generated />
namespace ABSOLUTE_CINEMA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Pr1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pr1));
        
        string IMigrationMetadata.Id
        {
            get { return "202505141927361_Pr1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
